import {
  collection,
  onSnapshot,
  orderBy,
  query,
} from "firebase/firestore";
import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";
import Message from "../components/message";
import { auth, db } from "../utils/firebase";

export default function Home() {
  // Create a state with all the posts
  const [allPosts, setAllPosts] = useState([]);

  const getPosts = async () => {
    const collectionRef = collection(db, "posts");
    const q = query(collectionRef, orderBy("timestamp", "desc"));
    const data = onSnapshot(q, (snapshot) => {
      setAllPosts(snapshot.docs.map((doc) => ({ ...doc.data(), id: doc.id })));
    });

    return data;
  };

  useEffect(() => {
    getPosts();
  }, []);

  return (
    <>
      <Head>
        <title>Blogri { auth.currentUser ? `- ${auth.currentUser.displayName}` : ''}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="text-lg font-medium mb-6">
        <h1 className="dark:text-sky-100">Nézzük, mit mondtak eddig...</h1>
        {allPosts.map((post) => (
          <Message {...post} key={post.id}>
            <Link href={{ pathname: `/${post.id}`, query: { ...post } }}>
              <button className="text-sm">
                Hozzászólások (
                {post.comments?.length > 0 ? post.comments?.length : 0})
              </button>
            </Link>
          </Message>
        ))}
      </div>
    </>
  );
}
